"""add_extended_order_details

Revision ID: c24630404e72
Revises: fcbcbd98f5b3
Create Date: 2026-04-29 15:44:23.309551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24630404e72'
down_revision: Union[str, None] = 'fcbcbd98f5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('responsible_personnel', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('order_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('promised_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('requirement_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('penalty_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'penalty_date')
    op.drop_column('orders', 'requirement_date')
    op.drop_column('orders', 'promised_date')
    op.drop_column('orders', 'order_date')
    op.drop_column('orders', 'responsible_personnel')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
